### ISSUE TITLE
Can't convert Go version 1.12.3 standard library

### ISSUE THREAD

**Issue by sorainnosia** [GridProtectionAlliance/go2cs#2]
Step to reproduce
1. Delete previous version of Golang by uninstalling it
2. Download Go version 1.12.3
3. Install it
4. Download go2cs and extract it
5. Install .NET 4.7.1 Dev Pack
6. Open go2cs solution on VS
7. Compile and successfully build go2cs.exe
8. Issue command :
    go2cs -s -r C:\\Go\src\\
    PAUSE
9. go2cs throws exception but there is no log, in console shows

===========================================================
Starting Go code pre-scan to update metadata...

Starting pre-scan of "C:\Go\src\archive\tar\common.go"...
    Finished.

Starting pre-scan of "C:\Go\src\errors\errors.go"...
    Finished.

Starting pre-scan of "C:\Go\src\fmt\doc.go"...
    Finished.

Starting pre-scan of "C:\Go\src\math\abs.go"...
    Finished.

Starting pre-scan of "C:\Go\src\os\dir.go"...
    Finished.

Starting pre-scan of "C:\Go\src\path\example_test.go"...
    Finished.

WARNINGS:
    example_test.go:5:0: Defined package clause "path_test" does not match file
path "C:\Go\src\path\example_test.go"

Starting pre-scan of "C:\Go\src\reflect\all_test.go"...
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at go2cs.ScannerBase.ExitExpression(ExpressionContext context) in D:\jkenedy\
Downloads\go2cs-master\go2cs-master\src\go2cs\ScannerBase_Expression.cs:line 68
   at GolangParser.ExpressionContext.ExitRule(IParseTreeListener listener) in D:
\jkenedy\Downloads\go2cs-master\go2cs-master\src\go2cs\Parser\GolangParser.cs:li
ne 6146
   at Antlr4.Runtime.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener,
IRuleNode r) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Ant
lr4.Runtime\Tree\ParseTreeWalker.cs:line 55
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 34
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IPar
seTree t) in D:\jkenedy\Downloads\go2cs-master\go2cs-master\src\Utilities\Antlr4
.Runtime\Tree\ParseTreeWalker.cs:line 32
   at go2cs.ScannerBase.Scan(Boolean showParseTree) in D:\jkenedy\Downloads\go2c
s-master\go2cs-master\src\go2cs\ScannerBase.cs:line 125
   at go2cs.PreScanner.Scan(Boolean _) in D:\jkenedy\Downloads\go2cs-master\go2c
s-master\src\go2cs\PreScanner.cs:line 60
   at go2cs.ScannerBase.ScanFile(Options options, String fileName, Boolean showP
arseTree, CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileN
eedsScan, SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2
cs-master\go2cs-master\src\go2cs\ScannerBase.cs:line 288
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 233
   at go2cs.ScannerBase.ScanImports(ScannerBase scanner, Boolean showParseTree,
CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan,
SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\
go2cs-master\src\go2cs\ScannerBase.cs:line 340
   at go2cs.ScannerBase.ScanFile(Options options, String fileName, Boolean showP
arseTree, CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileN
eedsScan, SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2
cs-master\go2cs-master\src\go2cs\ScannerBase.cs:line 314
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 233
   at go2cs.ScannerBase.ScanImports(ScannerBase scanner, Boolean showParseTree,
CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan,
SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\
go2cs-master\src\go2cs\ScannerBase.cs:line 340
   at go2cs.ScannerBase.ScanFile(Options options, String fileName, Boolean showP
arseTree, CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileN
eedsScan, SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2
cs-master\go2cs-master\src\go2cs\ScannerBase.cs:line 314
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 233
   at go2cs.ScannerBase.ScanImports(ScannerBase scanner, Boolean showParseTree,
CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan,
SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\
go2cs-master\src\go2cs\ScannerBase.cs:line 340
   at go2cs.ScannerBase.ScanFile(Options options, String fileName, Boolean showP
arseTree, CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileN
eedsScan, SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2
cs-master\go2cs-master\src\go2cs\ScannerBase.cs:line 314
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 233
   at go2cs.ScannerBase.ScanImports(ScannerBase scanner, Boolean showParseTree,
CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan,
SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\
go2cs-master\src\go2cs\ScannerBase.cs:line 340
   at go2cs.ScannerBase.ScanFile(Options options, String fileName, Boolean showP
arseTree, CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileN
eedsScan, SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2
cs-master\go2cs-master\src\go2cs\ScannerBase.cs:line 314
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 233
   at go2cs.ScannerBase.ScanImports(ScannerBase scanner, Boolean showParseTree,
CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan,
SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\
go2cs-master\src\go2cs\ScannerBase.cs:line 340
   at go2cs.ScannerBase.ScanFile(Options options, String fileName, Boolean showP
arseTree, CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileN
eedsScan, SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2
cs-master\go2cs-master\src\go2cs\ScannerBase.cs:line 314
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 233
   at go2cs.ScannerBase.ScanImports(ScannerBase scanner, Boolean showParseTree,
CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan,
SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\
go2cs-master\src\go2cs\ScannerBase.cs:line 340
   at go2cs.ScannerBase.ScanFile(Options options, String fileName, Boolean showP
arseTree, CreateNewScannerFunction createNewScanner, FileNeedsScanFunction fileN
eedsScan, SkippedFileScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2
cs-master\go2cs-master\src\go2cs\ScannerBase.cs:line 314
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 233
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 245
   at go2cs.ScannerBase.Scan(Options options, Boolean showParseTree, CreateNewSc
annerFunction createNewScanner, FileNeedsScanFunction fileNeedsScan, SkippedFile
ScanFunction handleSkippedScan) in D:\jkenedy\Downloads\go2cs-master\go2cs-maste
r\src\go2cs\ScannerBase.cs:line 245
   at go2cs.PreScanner.Scan(Options options) in D:\jkenedy\Downloads\go2cs-maste
r\go2cs-master\src\go2cs\PreScanner.cs:line 107
   at go2cs.Program.RunConversion(Options options) in D:\jkenedy\Downloads\go2cs
-master\go2cs-master\src\go2cs\Program.cs:line 73
   at go2cs.Program.Main(String[] args) in D:\jkenedy\Downloads\go2cs-master\go2
cs-master\src\go2cs\Program.cs:line 38
===========================================================

Windows shows "go2cs Has Stopped Working"

Is it because Map/Channel is not yet implemented? But according to the doc it can compile Go standard library. May I know which version of Go can be successfully compiled it's Standard Library you tested?

**Comment by ritchiecarroll** [comment]
Yes, Channel and Map are remaining needed conversions - plus plenty of work before standard library can be completely converted. My attention is currently averted onto other _paying_ projects ;-) But this is a fun one if I can find find some more time to complete it - or if others are interesed...

**Comment by ritchiecarroll** [comment]
FYI - channel and map are now completed. Much progress here since you tried last, but still plenty to do...
